### ISSUE TITLE
[Feature request] Be able to use the wallpaper depth effect with widgets on LS

### ISSUE THREAD

**Issue by Void48** [Skittyblock/MoreComplications#1]
Title.
![image](https://github.com/Skittyblock/MoreComplications/assets/85196642/94abc3ce-ba71-42b6-955b-740702ed3c26)
Would be very cool! Also appreciate you making this tweak ❤️

**Comment by Void48** [comment]
![image](https://github.com/Skittyblock/MoreComplications/assets/85196642/f31d9bcc-10d3-4c74-b409-0477b743d52a)

**Comment by Skittyblock** [comment]
This is a little out of scope for this tweak, and would make more sense as a separate one.

That being said, I'm not sure how a depth effect would really work for the complications. Going off of the default wallpaper, two of those complications would just be invisible, which doesn't really make sense.

**Comment by Void48** [comment]
> This is a little out of scope for this tweak, and would make more sense as a separate one.
> 
> 
> 
> That being said, I'm not sure how a depth effect would really work for the complications. Going off of the default wallpaper, two of those complications would just be invisible, which doesn't really make sense.

Sorry I didn’t make it clear enough, not for the complications, but **for the clock**. The image I shared above isn't how the default iOS lock screen looks. When you add an LS widget, the clock depth effect stops working, and ideally, the image I shared is how I would love it to look. And you're right, it'd probably be better as a separate tweak. If you're interested in creating a new tweak, I'd be happy to donate some money! Maybe you should consider setting up Ko-fi. 👍 

I’m sure many other people would appreciate a tweak that keeps the clock depth effect when widgets are added 🙂

**Comment by Skittyblock** [comment]
Oh right, I totally forgot about that. That sounds pretty easy so I'll probably try and look into doing it.

**Comment by Skittyblock** [comment]
Update: overriding `FBSSceneSettings`'s `-(BOOL)pr_isDepthEffectDisallowed` works to enable the depth effect, but it covers up the complications in addition to the time, and I'm not sure how to change that.

**Comment by Void48** [comment]
> Update: overriding `FBSSceneSettings`'s `-(BOOL)pr_isDepthEffectDisallowed` works to enable the depth effect, but it covers up the complications in addition to the time, and I'm not sure how to change that.

Dang, that sucks. Hopefully u can figure it out, and thanks again for looking into it. 🙏
